# Generated by Django 4.2.3 on 2023-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('delivery_method', models.CharField(choices=[('Pick-up Point', 'Pick-up Point'), ('Home Delivery', 'Home Delivery')], max_length=64)),
                ('shipment_cost', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=12)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
            ],
        ),
    ]
