# Generated by Django 4.2.3 on 2023-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('order_number', models.PositiveIntegerField()),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_date', models.DateField()),
                ('location', models.CharField(max_length=64)),
                ('delivery_method', models.CharField(choices=[('Pick-Up Point', 'Pick-Up Point'), ('Home Delivery', 'Home Delivery')], max_length=15)),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
