# Generated by Django 4.2.1 on 2023-06-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('refund_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('processed_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
