# Generated by Django 4.2.1 on 2023-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='product',
            field=models.CharField(default='fruits', max_length=50),
        ),
    ]
