# Generated by Django 4.2.3 on 2023-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('M-pesa', 'M-Pesa'), ('Pay on Delivery', 'Pay on Delivery')], max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_time', models.TimeField()),
                ('payment_date', models.DateField()),
                ('receipt_number', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=15)),
                ('reference_number', models.CharField(max_length=32)),
                ('products', models.CharField(max_length=64)),
            ],
        ),
    ]
